---
title: "Sample Weight Exploration"
author: "Joe Celebrezze"
date: "2023-10-09"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# packages
library(tidyverse)
library(here)
#library(lubridate)
#library(ggfortify)
library(ggpubr)
library(sjPlot) # for tab_model
library(psych) #for pairs.panels()
library(GGally) # For ggcorr()
library(scales)
library(lme4) # for lmer
#library(lmerTest) # to try stepwise selection
library(remef) # for remef
library(performance) # for multicollinearity check
library(car) # for qqPlot
library(gtools) # for combination()
library(kableExtra) # to make nice tables
library(glmmLasso) # specific to running lasso on generalized linear mixed models
library(glmnet) # 'best' package for running lasso on generalized linear models; also, has good function for cross-validation process

# defining functions
here = here::here
ggbiplot = ggbiplot::ggbiplot
select = dplyr::select
source(here('scripts', 'mem.selection.function.R')) #this is where mem.selection(), mem.selection.table() and mallows.cp() functions are stored

# reading in data
flamm.df <- read.csv(here('data', 'processed-data', 'main_dataset.csv')) %>% 
  filter(leaf_lfm > 0)
```

# Scatterplots
```{r}
flamm.df %>% 
  pivot_longer(cols = c(leaf_mass_ratio, leaf_lfm, stem_lfm, lfm, leaf_dmc, stem_dmc, dmc, LMA, branch_volume, branching, mpa, no_branches), names_to = 'exp_var', values_to = 'exp_val') %>% 
  mutate(exp_var = fct_relevel(as.factor(exp_var), c('leaf_mass_ratio', 'branch_volume', 'branching', 'no_branches', 'leaf_lfm', 'stem_lfm', 'lfm', 'mpa', 'leaf_dmc', 'stem_dmc', 'dmc', 'LMA'))) %>% 
  ggplot(aes(y = sample_wt, x = exp_val, color = species)) +
    geom_point() +
    geom_smooth(method = 'lm', se = F) +
    facet_wrap(~exp_var, scales = 'free') +
    scale_color_manual(values = c('#00468BB2', '#ED0000B2', '#42B540B2', '#0099B4B2', '#925E9FB2', '#AD002AB2', '#ADB6B6B2', '#1B1919B2')) +
    theme_bw() +
    labs(y = 'Sample Weight (g)', x = 'Explanatory Variable', color = 'Species') +
    theme(legend.position = 'top',
          axis.title = element_text(face = 'bold', size = 16),
          axis.text = element_text(size = 14),
          legend.title = element_text(face = 'bold', size = 16),
          legend.text = element_text(size = 14))
ggsave(here('figures', 'EDA', 'sample_wt', 'regressions.png'), height = 10, width = 12)
```

## By Species
```{r}
explanatory_var <- c('leaf_mass_ratio', 'branch_volume', 'branching', 'no_branches', 'leaf_lfm', 'stem_lfm', 'lfm', 'mpa', 'leaf_dmc', 'stem_dmc', 'dmc', 'LMA')
explanatory_labs <- c('Leaf Mass Ratio', 'Branch Volume', 'Branching', '# of Branches', 'Leaf LFM', 'Stem LFM', 'LFM', 'Water Potential', 'Leaf DMC', 'Stem DMC', 'DMC', 'Leaf Mass per Area')

sw.df <- flamm.df %>% 
  select(leaf_mass_ratio, branch_volume, branching, no_branches, leaf_lfm, stem_lfm, lfm, mpa, leaf_dmc, stem_dmc, dmc, LMA, species, sample_wt)

for(i in 1:length(explanatory_var)){
sw.df %>% 
  ggplot(aes(y = sample_wt, x = sw.df[,i], color = species)) +
    geom_point() +
    geom_smooth(method = 'lm') +
    facet_wrap(~species, scales = 'free') +
    scale_color_manual(values = c('#00468BB2', '#ED0000B2', '#42B540B2', '#0099B4B2', '#925E9FB2', '#AD002AB2', '#ADB6B6B2', '#1B1919B2')) +
    theme_bw() +
    labs(y = 'Sample Weight (g)', x = explanatory_labs[i], color = 'Species') +
    theme(legend.position = 'top',
          axis.title = element_text(face = 'bold', size = 16),
          axis.text = element_text(size = 14),
          legend.title = element_text(face = 'bold', size = 16),
          legend.text = element_text(size = 14))
ggsave(here('figures', 'EDA', 'sample_wt', paste0('spp_', explanatory_var[i],'.png')), height = 10, width = 12)
}
```

# MEM
## Data Wrangling
```{r}
mem.df <- flamm.df %>% 
  filter(ignition != '0') %>% 
  filter(species != 'ARCDEN', species != 'HETARB') %>% 
  unite('plant_id', c(species, plant), sep = '_', remove = F) %>% 
  select(species, sample_wt, leaf_mass_ratio, leaf_lfm, stem_lfm, lfm, leaf_dmc, stem_dmc, dmc, LMA, branch_volume, branching, mpa, no_branches, plant_id) %>% 
  mutate(sample_wt = scale(sample_wt), leaf_mass_ratio = scale(leaf_mass_ratio), leaf_lfm = scale(leaf_lfm), stem_lfm = scale(stem_lfm), lfm = scale(lfm), leaf_dmc = scale(leaf_dmc), stem_dmc = scale(stem_dmc), dmc = scale(dmc), LMA = scale(LMA), branch_volume = scale(branch_volume), branching = scale(branching), mpa = scale(mpa), no_branches = scale(no_branches)) %>% 
  drop_na(leaf_mass_ratio, leaf_lfm, stem_lfm, lfm, leaf_dmc, stem_dmc, dmc, LMA, branch_volume, branching, mpa, no_branches)

mem.predictors.df <- mem.df %>% 
  select(leaf_mass_ratio, leaf_lfm, stem_lfm, lfm, leaf_dmc, stem_dmc, dmc, LMA, branch_volume, branching, mpa, no_branches, species)

mem2.predictors.df <- mem.df %>% 
  select(leaf_mass_ratio, leaf_lfm, stem_lfm, leaf_dmc, stem_dmc, species)
```

## Model Selection 1
```{r}
sw.mem.selection <- mem.selection('sample_wt', mem.predictors.df, mem.df)
sw.model.df <- sw.mem.selection[[1]]
sw.mod.list <- sw.mem.selection[[2]]
sw.top.mem <- mem.selection.table(sw.model.df, sw.mod.list, 'SampleWt_MEM.html') %>% 
  mutate(flam.var = 'sample_wt')
```

## Model Selection 2
```{r}
sw2.mem.selection <- mem.selection('sample_wt', mem2.predictors.df, mem.df)
sw2.model.df <- sw2.mem.selection[[1]]
sw2.mod.list <- sw2.mem.selection[[2]]
sw2.top.mem <- mem.selection.table(sw2.model.df, sw2.mod.list, 'SampleWt_MEM.html') %>% 
  mutate(flam.var = 'sample_wt')
```

